:memo: Add brand guidelines for the brand assets
devfolioco/brand-assets pull request #1
Opened 2022-05-17 08:29 UTC by pragdua

🚧 

Brand guidelines for the Devfolio brand-assets README

2022-05-17 13:30 UTC, prateek3255 requested changes

2022-05-17 13:30 UTC, prateek3255 commented on README.md
>  # brand-assets
We can remove this

2022-05-17 13:30 UTC, prateek3255 commented on README.md
> +## Devfolio Brand Assets
Change this to a h1(#)

2022-05-17 13:30 UTC, prateek3255 commented on README.md
> +- `White`<img src ="Logo + Text - White/Devfolio - White.png" style="width: 100px; background-color: #2F3437; padding: 8px 10px 8px 10px; border-radius: 8px;margin-left: 20px; ">
This looks kind of weird right now, would look nice if it was center aligned, and had some gap between the text and the logo
<img width="265" alt="image" src="https://user-images.githubusercontent.com/21277179/168822584-3aa546b8-48ed-4e9d-a0aa-3d7fdc67d02f.png">

2022-05-17 13:39 UTC, prateek3255 requested changes

2022-05-17 13:39 UTC, prateek3255 commented on README.md
> +- Associated advertisements, media, websites with the aforementioned hackathons are permitted to use the Devfolio branding under this condition too.
Shouldn't this be:
```suggestion
3 Associated advertisements, media, websites with the aforementioned hackathons are permitted to use the Devfolio branding under this condition too.
```

2022-05-18 06:48 UTC, parzuko commented
@pragdua Would be super helpful if you could share the output markdown content in the PR description!

2022-05-26 08:28 UTC, prateek3255 approved these changes

2022-05-26 08:28 UTC, chtushar approved these changes

2022-05-26 08:28 UTC, merged